### ISSUE TITLE
CAD?

### ISSUE THREAD

**Issue by maclakey** [Shpyda/2.4_350mm_Clean_Electronics_Bay_Mod#1]
Any chance you could upload the CAD files?  I'd like to modify this to better suit my particular printer.

**Comment by maclakey** [comment]
I solved my issue.

**Comment by Shpyda** [comment]
Glad you got it resolved. Let me know if you have any other issues.On Jan 16, 2023, at 12:59 PM, maclakey ***@***.***> wrote:﻿
I solved my issue.
